name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-cpu:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: INSTALL .NET CORE
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: SETUP MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: BUILD
        run: dotnet build

      - name: TEST
        run: dotnet test

      - name: IRIS
        run: dotnet run --project tests/iris.csproj

