name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-cpu:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
      - name: Get Latest
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: SETUP MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test

      - name: Test
        run: dotnet run --project tests/tests.csproj

